### ISSUE TITLE
Keeps crashing

### ISSUE THREAD

**Issue by rawadnassif** [nazuke/SEOMacroscope#11]
It keeps crashing after 2-3 minutes. Not sure why though.

**Comment by nazuke** [comment]
Thank you very much for your interest in SEO Macroscope rawadnassif.

OK, there are probably many reasons why this may be happening; I'm afraid that you have probably uncovered a bug.

Would it be possible to run a few tests against the website that manifests this fault please?

(Please note, I am currently right in the middle of writing HTTP/2 support, under the 1.7 branch, so it may take a little while to resolve this issue going forwards.)

many thanks

Jason

**Comment by rawadnassif** [comment]
Thank you for your response. It seems to be working for my colleague, however when the crawl was complete for a specific section of the site, we realized that it it crawled 20 out 800 pages. You think we did something wrong there or is it an already identified bug?

**Comment by nazuke** [comment]
This issue has hopefully now been resolved with the release of v1.7.
