### ISSUE TITLE
using seomacroscope 

### ISSUE THREAD

**Issue by harvinderpuri** [nazuke/SEOMacroscope#17]
Hello All,

I am using SEOMacroscope from last few months. 
I need to understand what exact   Crawled Date,  Server Date and Modified Date  are ?
Could anyone solve my this query.

Thanks in advance.

**Comment by nazuke** [comment]
Hi @harvinderpuri,

Please note that some of these details may have been changed in the newer 1.7 branch.

Very briefly:

* **Crawled Date**: This is the date/time when SEO Macroscope retrieved that particular page from the website.

* **Server Date**: This date field depends on how the web server was configured. This value will normally be extracted from the HTTP "Date" field: https://en.wikipedia.org/wiki/List_of_HTTP_header_fields* 

**Modified Date**: This date field depends on how the web server was configured, and whether the crawled document in question has a Last-Modified set. This value will normally be extracted from the HTTP "Last-Modified" field: https://en.wikipedia.org/wiki/List_of_HTTP_header_fields
