### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by Stefanp44** [nazuke/SEOMacroscope#20]
Hi,

On every website I created, I get an error 400. Is it because I use Wordfence or BBQ plugins? Is there something I should whitelist to be able to use SEOMacroscope? I just noticed I get the same error on a fresh install, no plugin: could it be the host? Thanks in advance for your answer.

Regards,

**Comment by nazuke** [comment]
Many thanks @Stefanp44

OK, this looks like it's definitely a bug on the SEO Macroscope side of things. I don't think that this is a problem with Wordfence at this stage.
I did not notice this before, but I think that I'm getting different behaviour in debug and release build of the application.
For example, if you scan the SEO Macroscope site at https://nazuke.github.io/, and then click one of the URLs, and look in the "HTTP Headers" tab on the bottom panel, you should see the HTTP headers that were sent in the request.
This appears to work as expected in the debug build, but in the release build from the installer and in VS2017, I'm only seeing the "Host" HTTP header listed.
If these are the HTTP headers actually being sent in a request, then it explains why some web servers are throwing back a 400 (Request not understood) response.

regards

Jason

**Comment by nazuke** [comment]
So far, I am seeing different behaviour with regards to the preparing of the outgoing request's HTTP Headers in DEBUG and RELEASE builds.

If "Optimize code" is switched on in the release build, the outgoing headers break. If it is switched off, it compiles the headers as normal.

My guess is that a critical piece of code may be getting optimized away.

**Comment by nazuke** [comment]
Hi @Stefanp44, I released a new v1.7.1.0 version of SEO Macroscope last night.

Hopefully, this resolves the issue that you reported.

What I found, was that the production User-Agent header was malformed, which resulted in incorrect HTTP Headers were being sent for each request. This means that on well-configured websites, these requests would probably be rejected.

In the end, it's unlikely that it's a problem with Wordpress/Wordfence.

If you would like to use SEO Macroscope, and do find that you need to whitelist it's user agent string with Wordfence, then it currently follows a pattern like this:

    SEO-Macroscope/1.7.1.0

...where the version number will change with each new version.

The outgoing User-Agent HTTP Header can also be found during a scan by clicking on one of the crawled documents in the "Structure Overview" panel, and then clicking the "HTTP Headers" tab in the lower panel. On the left, you should see a list of green HTTP Headers that are sent by SEO Macroscope. The exact headers will likely vary from machine to machine.

I'll close this issue now. Please open a new one if the same problem persists in the new version.

Many thanks for spending your time on this.
