### ISSUE TITLE
Pasting a list of 100 urls and only 43 were scanned

### ISSUE THREAD

**Issue by semperaye** [nazuke/SEOMacroscope#21]
Is there a max number of urls that can be scanned in a batch? I pasted 100, and only 46 were scanned. I set my max pages to 100.

**Comment by semperaye** [comment]
Thanks for the reply. Similar thing happened this evening (with the new version) I was scanning a batch of around 1400 urls and just when it got to about 1370ish the program crashed lol....unfortunately I didn't grab the error code :(

**Comment by nazuke** [comment]
Hi @semperaye,

A lot has changed in v1.7.6 since this bug was first reported.

I'm closing this ticket for now, but please report a new issue if you have the same problem occurring again.

many thanks
