### ISSUE TITLE
Humans.txt URL gets keywords from automatic 404 page

### ISSUE THREAD

**Issue by celtic-coder** [nazuke/SEOMacroscope#24]
Hi Jason,

The Humans.Txt URL is generating its own set of keywords, even though it does not exist on the server.

## Humans.Txt URL with 404 Status

An example is [http://joelairdwoodturning.com/humans.txt](http://joelairdwoodturning.com/humans.txt) This is generating keywords from the automatically generated 404 page. This can be seen from the "Raw Document Text" tab of the page in SEOMacroScope: 

![humans-txt-keywords](https://user-images.githubusercontent.com/11787866/43609049-de88b05e-969a-11e8-825d-3c483f173030.png)
(Click image to open in a separate tab)

The "humans.txt" has a status of 404, but there is text associated with the page as can be seen in the tab below.

## Keyword-Analysis Excel report

The Keyword Report in Excel is reporting the keywords with the "Humans.Txt" URL. The screen shot below is for the two-word phrases:

![macroscope-keyword-analysis - excel](https://user-images.githubusercontent.com/11787866/43610642-9cea53ec-969e-11e8-8c9b-ea25b39b120c.png)

## Summary

This is inflating the correct keywords for the overall site as well as incorrectly giving extraneous keywords for a URL that does not exist on the server.

However, this is a minor bug in what is an excellent application! The fact that you are giving one-word, two-word, three-word and four-word phrases is an excellent feature as I mentioned in my [Tweet](https://twitter.com/AnDaraDeis/status/1024641199079084033) yesterday.

**Note:** The http://joelairdwoodturning.com/sitemap.xml URL is not generating any associated keywords in the Excel report. Therefore this 404 URL is working correctly.

Thanks!
Liam

**Comment by nazuke** [comment]
Many thanks for this very detailed report @celtic-coder, hopefully this bug should be fixed in the v1.7.4.0 out just now.

kind regards, Jason

**Comment by celtic-coder** [comment]
Hi Jason,

Thank you for addressing this issue! However, I am unable to test it as the one-word, two-word and the other keyword phrases are not showing.

Text indexing is enabled in Preferences:

![text-indexing-is-enabled](https://user-images.githubusercontent.com/11787866/45230287-538cc700-b2c0-11e8-9629-ab8933e6c21a.png)

However, the Keyword Analysis tabs on the right-hand side are blank:

![keyword-analysis-tabs-are-blank](https://user-images.githubusercontent.com/11787866/45230515-f6dddc00-b2c0-11e8-988b-b1dd46667b52.png)

Am I missing setting a preference that I did not notice in the previous version?

Thanks!
Liam

**Comment by nazuke** [comment]
This bug should now be eliminated.
