### ISSUE TITLE
Program hang on "ndoherty.com" website scan

### ISSUE THREAD

**Issue by celtic-coder** [nazuke/SEOMacroscope#25]
Version 1.7.3.0 (With Visual SEO Studio)
----------------------------------------

I was attempting to run SEOMacroScope on the
[https://ndoherty.com/](https://ndoherty.com/) website. The program hung shortly
after the scan started. I had previously started a scan with [Visual SEO
Studio](https://visual-seo.com/) (Community Edition). I do not know if this
might have interfered with the SEOMacroScope scan.

I have attached the program hang information for SEOMacroScope and the Event
Viewer information for Visual SEO Studio.

[Program Hang 1 - Previous Version.txt](https://github.com/nazuke/SEOMacroscope/files/2390452/Program.Hang.1.-.Previous.Version.txt)
[Program Hang 1 - Visual SEO Studio error.txt](https://github.com/nazuke/SEOMacroscope/files/2390453/Program.Hang.1.-.Visual.SEO.Studio.error.txt)

Version 1.7.3.0
---------------

Subsequently, I attempted the scan a further time, but without the Visual SEO
Studio application running. However, this also hung.

[Program Hang 2 - Previous Version.txt](https://github.com/nazuke/SEOMacroscope/files/2390458/Program.Hang.2.-.Previous.Version.txt)

Version 1.7.4.0
---------------

I re-ran the scan with the latest version. It ran for several hours - I am
guessing that there are over 15K URLs in the “ndoherty.com” website. However,
close to the end of the scan, the latest version also hung.

[Program Hang 3 - Latest Version.txt](https://github.com/nazuke/SEOMacroscope/files/2390462/Program.Hang.3.-.Latest.Version.txt)

### Note:

If it might be of any assistance, I have a “SEOMacroscopeSeriesOne.exe.8748.dmp”
file available for the last program hang.

**Comment by nazuke** [comment]
Hi Liam, many thanks for making this very detailed report!

In theory, there shouldn't be any interference between the two applications, it's very likely a coincidence.

I'm afraid that the dump file details are a little beyond me, but reading through them it appears that the hang is occurring when SEO Macroscope is updating the main display list currently being viewed.

It's possible that this is either a deadlock (i.e. two threads are trying to access the same piece of data), or else it is simply taking a really long time to grind through the results.

I will see if I can reproduce the fault in debug mode by scanning the http://ndoherty.com/ site when I have some time.

many thanks

Jason

**Comment by nazuke** [comment]
Hi @celtic-coder, I'm closing this issue for now.

Please open a new issue if the same problem is encountered in v.1.7.6 or later.

Alternatively, please give me a shout if you'd like me to try crawling the site in question from this end.
