### ISSUE TITLE
The problem with crawling pages on HTTPS.

### ISSUE THREAD

**Issue by Marek-lecian** [nazuke/SEOMacroscope#6]
Hello
I tried the tool and it looks good,
but on sites that have more security set up, they will write redirection information, which will end. 
It's not a problem for search engines and other crawlers. 
It's quite important to me because I do not have any HTTP site anymore

`HTTP/1.1 301 Moved Permanently 
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Connection: Upgrade, close
Cache-Control: max-age=0
Content-Type: text/html; charset=UTF-8
Date: Mon, 18 Sep 2017 19:51:34 GMT
Expires: Mon, 18 Sep 2017 19:51:34 GMT
Location: https://mareklecian.cz/
Server: Apache
`
https://www.michalspacek.cz/
Or
`HTTP/1.1 301 Moved Permanently 
Connection: close
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: no-referrer, strict-origin-when-cross-origin
X-Frame-Options: DENY
Content-Security-Policy: default-src 'none'; form-action 'none'; report-uri https://plz.report-uri.io/r/default/csp/enforce
Public-Key-Pins: pin-sha256="3bVocQCvVq54eZkK2+vZf6dCYvr9kj+vsU4z0mbn3gU="; pin-sha256="u6l/n/3zinL6L9SAayWa0tXu2dX+6J77WB/deOyKx1I="; pin-sha256="ET3FsZD2D9FewsIQe8t6986ajvmFXaBzNJDXYBnXLMw="; pin-sha256="5e1MASoMjR09CTL5WP1dFoR9yQBLrAkwdHVCB3aoBaA="; pin-sha256="N6hALJkpMWIA3mdMkpeJRwFFNwxWQmNsbcL70XBwxIo="; pin-sha256="YswPXsgfC9zcBFJRkWg9cA3e22TY08khzcragg8vxQo="; max-age=2592000; includeSubdomains; report-uri="https://plz.report-uri.io/r/default/hpkp/reportOnly"
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Content-Type: text/html; charset=utf-8
Date: Mon, 18 Sep 2017 19:47:16 GMT
Location: https://www.michalspacek.cz/
Server: <script/src=//xss.sk></script>
X-Powered-By: <script>document.write('<img src="//xss.sk" title="Inline JavaScript is bad, m\'kay?">');</script>
`

**Comment by nazuke** [comment]
Hello Marek,

Thank you very much for your feedback and interest, I really appreciate this.

I looked at your websites' home page, those are two different websites, is that correct?

If I've read your notes correctly, you mean that a crawl that redirects from:

> http://mareklecian.cz/

...to:

> https://mareklecian.cz/

...is failing to handle that redirect correctly?

I may very well have missed something in this type of case. But normally, a HTTP to HTTPS redirect for the *same* domain should be handled.

The "Follow redirects" option is off by default, but enabling it may solve this example. It's normally off, to circumvent infinite crawls. There's also the option of adding patterns for each "internal" site to the Task Parameters -> Include dialogue.

Can I have your permission to briefly test a few crawls against your site(s) please? I would only need to follow the first few pages to test the redirect functionality.

Many thanks, and kind regards,

Jason

**Comment by Marek-lecian** [comment]
Hello Jason,
You can try to crawle my website.
By default, I had a site on HTTP and added redirect 301 to HTTPS.
It works  years for crawlers in Google, Bing, Yandex, Seznam.cz etc.
I have never had problems with the redirector or the users.

What is wrong is that on these sites it looks like it is redirect from 
https://mareklecian.cz/
on
https://mareklecian.cz/
which i think is bug.

This is the case with any URL

He always downloads
https://mareklecian.cz/ 301  <
https://mareklecian.cz/sitemap.xml 301
https://mareklecian.cz/robots.txt 200
 
I'm suspicious that maybe the tool to work with certificates (I use lettingscrypt.org) or other elements of a secure site on HTTPS (preload etc.)

Many thanks, and kind regards,

Mark

**Comment by nazuke** [comment]
Hello Marek,

Thank you very much for your permission, I will try and be as quick as possible.

Please note, you should see any scans I produce in your logs with the user-agent:

> SEO Macroscope / DEVELOPER MODE

I've made that a little more explicit than the previous value of "BOT".

It might take a little while, but I shall add my findings here.

Many thanks again for your interest with this project,

Jason

**Comment by nazuke** [comment]
Hello Marek,

It looks like that site is using HTTP/2. That is what I am seeing when comparing the request/response in Firefox with what my own code sends/receives. I'm also seeing the same behaviour when crawling with Xenu. Screaming Frog seems to work just fine, albeit it a little slow from here.

This may be tricky to solve, as from what I can tell, it's not currently clear if C#'s WebClient supports HTTP/2 properly yet. This is something that needs to be solved, as I have no doubt that we'll see more examples like this.

From what I can tell, the initial request to http://mareklecian.cz/ works. It follows the redirect to https://mareklecian.cz/. From what I can tell, that page then tries to "upgrade" the HTTP/1.1 connection to HTTP/2; this fails. From my code's point of view, the response returned tries to go into an infinite redirect loop. These are the HTTP Headers that I receive for https://mareklecian.cz/ :

    HTTP/1.1 301 Moved Permanently 
    Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
    Connection: Upgrade, close
    Cache-Control: max-age=0
    Content-Type: text/html; charset=UTF-8
    Date: Fri, 22 Sep 2017 06:26:18 GMT
    Expires: Fri, 22 Sep 2017 06:26:18 GMT
    Location: https://mareklecian.cz/
    Server: Apache

I'm going to leave this issue open for now. But may close it and open an HTTP/2 specific issue soon.

Many thanks for your interest in this project,

Jason

**Comment by Marek-lecian** [comment]
It's great that you found it. ;) Jason
Thank you.

I wish good luck with the developments.

**Comment by nazuke** [comment]
Thanks again Marek,

This is proving to be a puzzle. It seems that right now, support for HTTP/2 is limited client-side with C# and .NET. Support is fine on the server-side, though.

The strange thing is, in this particular case, the client/server *should* drop back to using HTTP/1.1; but that does not appear to be the case.

Either way, I'm investigating if I can use one of the HTTP/2 libraries available for C# and .NET, and upgrade to the official way once that support arrives.

Of course, I'm using SharpDevelop to build this, so I may also investigate if this is solvable by upgrading the project to VisualStudio.

many thanks

Jason

**Comment by nazuke** [comment]
OK, after some research, I've begun work on adding HTTP/2 support.

I'm also taking the opportunity to consolidate the scattered HTTP requests throughout the application into a centralized location, so that issues like this HTTP/2 one can be handled more easily in future.

**Comment by Wardrop** [comment]
I seem to also be running into this issue. I think Nginx defaults to using http/2 in more recent versions, so I imagine any Nginx powered site is going to hit this snag.

**Comment by nazuke** [comment]
(Belated) Thanks Wardrop.

I'm not sure if Marek-lecian has since changed his server configs, but at the time, I got a second opinion of the problem by attempting to crawl his URL with Xenu; which immediately got "stuck". I suspect that the web server may not have had HTTP/1.1 configured as a fallback for older, non-HTTP/2 user-agents.

Marek-lecian's website is showing in the Firefox debugger that it's speaking HTTP/2.

I had no problem when trying with Screaming Frog. Which appears to support HTTP/2 nicely.

Currently, Xenu appears to be able to crawl Marek-lecian's site as HTTP/1.1 now.

At the time, I was using the older HTTP .NET classes, which appear to lack support for HTTP/2, and hence choked when encountering an HTTP/2-only web server. It was important to support the ability to crawl any potential HTTP/2-only websites anyway. It's taken a while to rewrite most of the HTTP-handling code, as what was required differed quite a lot from the original code; along with various knock-on side effects.

many thanks!

**Comment by nazuke** [comment]
This issue has hopefully now been resolved with the release of v1.7.

**Comment by harvinderpuri** [comment]
Hello Nazuke,

I am unable to screen my website after migration from http to https. The tool scans only two pages of my website.
https://www.punjabkesari.in/

**Comment by nazuke** [comment]
Hi @harvinderpuri, can I check that you're on the most recent release 1.7.3?

I took a quick look at your site with SEO Macroscope 1.7.3 (using default preferences), and was able to scan some way into the site. I cancelled after watching it get a little way.
