### ISSUE TITLE
The installer does not seem to install anything

### ISSUE THREAD

**Issue by Dh42** [nazuke/SEOMacroscope#9]
It says the installation completed, but there are no new created files. Tested on windows 10.

**Comment by nazuke** [comment]
Thank you for reporting this Lesley. I'll be investigating this shortly, but first, can you confirm that you are on a 64 bit Windows, and attempted this install with release v1.6 of SEO Macroscope?

Many thanks,

Jason

**Comment by Dh42** [comment]
I am on 64 win 10. I tried the latest release of when I posted. I also tried the release before as well. It is not creating a directory or files, even though it says it is.

**Comment by nazuke** [comment]
This issue has hopefully now been resolved with the release of v1.7.
